curation-172 API-Create-Publication Models for Creating Publication
EBISPOT/gwasdepo-commons pull request #74
Opened 2023-01-04 12:41 UTC by sajo-ebi

2023-01-20 15:41 UTC, sprintell requested changes
Hi @sajo-ebi  the junicode code package and files are still in the code bsse, since the dependecy has been added to the pom file, we should remove this

2023-01-20 15:41 UTC, sprintell commented on src/main/java/uk/ac/ebi/spot/gwas/deposition/junidecode/Junidecode.java
> +/*
Hi @sajo-ebi  the junicode code package and files are still in the code bsse, since the dependecy has been added to the pom file, we should remove this

2023-01-20 15:41 UTC, sprintell commented on src/main/java/uk/ac/ebi/spot/gwas/deposition/junidecode/X00.java
> +/*
junicode codebase and others below  should be removed

2023-01-20 15:45 UTC, sprintell approved these changes

2023-01-23 12:00 UTC, sajo-ebi commented on src/main/java/uk/ac/ebi/spot/gwas/deposition/junidecode/Junidecode.java
> +/*
@sprintell the Junidecode changes has been removed from codebase before the PR, I checked the branch can't see any code for Junidecode, probably you are checking the old commit files , the latest commit doesn't have these changes

2023-01-23 12:00 UTC, sajo-ebi commented on src/main/java/uk/ac/ebi/spot/gwas/deposition/junidecode/X00.java
> +/*
@sprintell the Junidecode changes has been removed from codebase before the PR, I checked the branch can't see any code for Junidecode, probably you are checking the old commit files , the latest commit doesn't have these changes

2023-01-23 12:01 UTC, merged